"""empty message

Revision ID: e55158e0ae02
Revises: 
Create Date: 2018-03-14 00:44:09.959761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55158e0ae02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('user_ID', sa.String(length=255), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=False),
    sa.Column('LastName', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('Email', sa.String(length=80), nullable=False),
    sa.Column('Location', sa.String(length=255), nullable=False),
    sa.Column('Biography', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=80), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=20), nullable=False),
    sa.PrimaryKeyConstraint('user_ID'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserProfile')
    # ### end Alembic commands ###
